import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import clsx from "clsx";

import Header from "./Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "max-w-6xl mx-auto")}>
        <ClerkProvider>
          <Header />
          <div className="mt-5">{children}</div>
        </ClerkProvider>
      </body>
    </html>
  );
}
